# autogenerated by txs
\dotsint#S
\fint#S
\iiiint#S
\iiint#S
\iint#S
\int#S
\landdownint#S
\landupint#S
\oiint#S
\oint#S
\ointclockwise#S
\ointctrclockwise#S
\sqiint#S
\sqint#S
\varoiint#S
\varointclockwise#S
\varointctrclockwise#S
