# autogenerated by txs
#include:defpattern
#include:fp-addons
#include:fp-basic
#include:fp-eqn
#include:fp-eval
#include:fp-exp
#include:fp-pas
#include:fp-random
#include:fp-snap
#include:fp-trigo
#include:fp-upn
\message#S
\message{arg1}#S
