# autogenerated by txs
#include:trig
\DeclareGraphicsExtensions{arg1}#S
\DeclareGraphicsRule{arg1}#S
\GDebug#S
\Gin#S
\Grot#S
\Gscale#S
\csname#S
\do#S
\expandafter#S
\graphicspath{arg1}#S
\includegraphics#S
\noexpand#S
\reflectbox#S
\resizebox#S
\rotatebox{arg1}#S
\scalebox{arg1}#S
