# autogenerated by txs
#include:\MD@default@family
#include:ifthen
#include:keyval
\ProcessUnusedOptions{arg1}#S
\WarningIfLoadedNoOption{arg1}#S
\WarningIfLoaded{arg1}#S
\ficshape{arg1}#S
\fscshape{arg1}#S
\selectgreekfamily{arg1}#S
